### ISSUE TITLE
No implementation found for method setAccelerationSamplingPeriod

### ISSUE THREAD

**Issue by matifdeveloper** [AliEren04/step_sync#1]
```
E/flutter (23178): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setAccelerationSamplingPeriod on channel dev.fluttercommunity.plus/sensors/method)
E/flutter (23178): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (23178): <asynchronous suspension>
E/flutter (23178): 
```

**Comment by AliEren04** [comment]
The issue has been resolved. The accelerometer setup is now functioning as expected. Closing the issue.

Additionally, package updates have been made, likely due to outdated dependent packages. Structural changes were also implemented, and a new major version has been released. Everything is now working correctly, and soon all formal testing will be performed.
